### ISSUE TITLE
Server restart message

### ISSUE THREAD

**Issue by ParadiseNICK** [Quantum64/Arcade-Issues#39]
Rather than a rainbow, make it

&c&l

(red)(bold)

**Comment by Quantum64** [comment]
But the rainbow is so nice :disappointed:

**Comment by Quantum64** [comment]
![image](https://cloud.githubusercontent.com/assets/3969183/15085792/5510c976-13aa-11e6-9592-72d2385f5f95.png)

Fixed in build 2164
