### ISSUE TITLE
Time Alive on Pets (cosmetic gui)

### ISSUE THREAD

**Issue by ParadiseNICK** [Quantum64/Arcade-Issues#41]
https://gyazo.com/b8ec1c6d7a773308fc078a8b6b4486f4

"Time Alive:"

is this in seconds, minutes, hours? should also be rounded to nearest highest increment (secs, mins, hours, days, yrs)

**Comment by Quantum64** [comment]
This is actually a bug

Also @RazzerBlade remember that cosmeticsmenu tag is for issues with the actual /cosmetics menu, and also add the core tag for any issues relating to cosmetics

**Comment by Quantum64** [comment]
Fixed in build 1262

**Comment by Quantum64** [comment]
![image](https://cloud.githubusercontent.com/assets/3969183/15085971/a84befc0-13ab-11e6-9b84-f3b575c4edb6.png)
