### ISSUE TITLE
Kill Effect not working

### ISSUE THREAD

**Issue by BladeVapes** [Quantum64/Arcade-Issues#42]
The "Notes Kill Effect" does not work.
With the other kill effects it shows a piece of redstone but with the notes one it shows paper, Like what you would see with a title. 

http://i.imgur.com/o7hHeYs.png

**Comment by Quantum64** [comment]
@RazzerBlade Effects are particle effects and remember to add core too

**Comment by Quantum64** [comment]
Fixed in build 2160

**Comment by Quantum64** [comment]
Previously unboxed ones will stay paper, but will function, newly unboxed ones will will be redstone and function as well

**Comment by Quantum64** [comment]
@RazzerBlade Remember cosmeticsmenu is the first menu you see with /cosmetics.  This was an issue with myitems

**Comment by Quantum64** [comment]
Confirmed fix
